<?php

namespace app\admin\controller;

use QL\QueryList;
use think\Controller;
use think\Request;

class Collect extends Base
{
    public $config;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->config = model('admin/Config');
    }

    /**
     * 显示资源列表
     *
     * @return \think\Response
     */
    public function index()
    {
        //

        return $this->fetch();
    }

    /**
     * 抓取规则
     */
    public function rule(){

        if($this->request->isPost()){
            $params = $this->request->param();
            $rule = json_decode($params['rule'],true);
            $key[] =
                [
                'type'  => 'checkbox',
                'fixed' => 'left',
                ];


            foreach ($rule as $k => &$v){
                if( count($v) < 3 ){
                    return $this->error('规则格式错误');
                }
                $key[] = [
                    'field'  => $k,
                    'title' => $v[2]
                ];
                unset($v[2]);
            }

            $key[] =[
                "fixed"     => 'right',
                "width"     => 165,
                "align"     => 'center',
                "toolbar"   => '#barDemo',
            ];

            $i = 0;
            $row = [];
            while ( $i <= $params['page']){
                // 待采集的页面地址
                $url = $i == 0 ? $params['url']:$params['url'].$i.'/';
                // 切片选择器
                $range = '#cardslist>.card';

                $data = QueryList::Query($url,$rule,$range)->data;
                $row = array_merge($row,$data);
                $i++;
            }


            return $this->success('查询成功','', ['key'=>$key,'data'=>$row]);
        }

        return $this->fetch();
    }

}
