<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/10/5
 * Time: 15:09
 */

namespace app\admin\controller;


use app\admin\model\AdminLog;

class Order extends Base
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 订单列表
     */
    public function orderList(){
        if ($this->request->isAjax()) {

            $map['keyword'] = $this->request->get('keyword', '');
            $map['status']  = $this->request->get('status', '');

            $data = [
                'code'  => 0,
                'msg'   => '数据返回成功',
            ];

            AdminLog::setTitle('获取页面模板列表');
            return json($data);
        }else{

            $config= [];
            $this->assign('config',$config);
            return $this->fetch();
        }
    }

    /**
     * 编辑订单
     */
    public function orderForm(){
        if ($this->request->isAjax()) {

            $map['keyword'] = $this->request->get('keyword', '');
            $map['mobile']  = $this->request->get('mobile', '');
            $map['sex']     = $this->request->get('sex', '');
            $map['status']  = $this->request->get('status', '');

            $data = [
                'code'  => 0,
                'msg'   => '数据返回成功',
            ];

            AdminLog::setTitle('编辑订单');
            return json($data);
        }else{
            return $this->fetch();
        }
    }

    /**
     * 删除订单
     */
    public function orderDel(){
        $ids = array_unique(input('post.id/a', []));
        foreach ($ids as $val) {
            if ($val == 1 || $val == 2) {
                $this->error('禁止删除普通用户或游客分组');
            }
            if ($this->userRole->where('pid', $val)->where('status', 1)->find()) {
                $this->error('该角色分类下存在子角色，删除失败');
            }
            $rs = $this->userRole->where('id', $val)->setField('status', '-1');
            if (!$rs) {
                $this->error('删除失败');
            }
        }
        unset($val);
        AdminLog::setTitle('删除用户角色');
        $this->success('删除成功');
    }

}