<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/9/14
 * Time: 23:34
 */

namespace app\api\controller;


use think\Controller;

class Base extends Controller
{
    function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}