<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/9/16
 * Time: 13:16
 */

namespace app\api\controller;


class System extends Base
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 配置文件基础信息
     */
    public function base(){
        $url = 'http://open.ewei.com';

        $result = [
            'error'   => 0,
            'message' => '注册成功',
            'data' => [

                'url' => $url,
            ]
        ];

        return json($result);
    }
}