<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/9/30
 * Time: 16:34
 */

namespace app\api\controller;


use think\Controller;
use think\Db;
use think\Exception;
use app\common\model\Activity as ActivityModel;

class Task extends Controller
{
    protected $activity;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->activity         =  new ActivityModel();
    }

    /**
     * 修改活动状态
     */
    public function updateActivityStatus(){
        $row = $this->activity->where('status','not in','3,4')->select();
        $time = time();
        foreach ($row as $k=>$v){
            if( ( $v['depart_time'] + $v['expend_time']*60 - $time ) <=0 ){
                Db::name('activity')->where(['id'=>$v['id']])->update(['status'=>3]);
            }
        }
    }
}